name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    name: Build for (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x86_64
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x86_64
          - name: macOS
            os: macos-latest
            target: aarch64-apple-darwin
            arch: aarch64

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        if: matrix.os == 'windows-latest'
        with:
          arch: x64
      - name: Setup Rust toolchain
        run: |
          rustup toolchain install

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"

      - name: Build
        run: |
          cargo build --release --all-targets --all-features --workspace --target ${{ matrix.target }}

      - name: Rename
        if: matrix.os == 'windows-latest'
        run: Rename-Item -Path ".\target\${{ matrix.target }}\release\zw-rs.exe" -NewName "zw-rs"

      - name: Upload release
        uses: actions/upload-artifact@v7
        with:
          name: zw-rs-${{ matrix.arch }}-${{ matrix.name }}
          path: "./target/${{ matrix.target }}/release/zw-rs"

  telegram:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Upload to Telegram
    needs: run
    runs-on: ubuntu-latest
    permissions: {}
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      COMMIT_URL: ${{ github.event.head_commit.url }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: ./artifacts
      - name: Upload to Telegram
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            mv ./artifacts/zw-rs-x86_64-Windows/zw-rs ./zw-rs-x86_64-windows.exe
            mv ./artifacts/zw-rs-x86_64-Linux/zw-rs ./zw-rs-x86_64-linux
            mv ./artifacts/zw-rs-aarch64-macOS/zw-rs ./zw-rs-aarch64-macos
            ESCAPED=`python3 -c 'import json,os,urllib.parse; msg = json.dumps(os.environ["COMMIT_MESSAGE"]); print(urllib.parse.quote(msg if len(msg) <= 1024 else json.dumps(os.environ["COMMIT_URL"])))'`
            curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHAT_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fwindows%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Flinux%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fmacos%22%2C%22caption%22:${ESCAPED}%7D%5D" -F windows="@./zw-rs-x86_64-windows.exe" -F linux="@./zw-rs-x86_64-linux" -F macos="@./zw-rs-aarch64-macos"
          fi
